extends ProgressBar

export var fGColorString: String = "STYLEBOXFLAT_NORMAL_FG_COLOR1"
export var fontColorString: String = "FONT_COLOR_TRANSPARENT"

func _ready():
	UIManager.SetNewStyleBoxFlat(self, "bg", UIManager.COMMONPROGRESSBAR_STYLE.STYLEBOXFLAT_NORMAL_BG_COLOR, UIManager.COMMONPROGRESSBAR_STYLE.STYLEBOXFLAT_NORMAL_BORDER_WIDTH, UIManager.COMMONPROGRESSBAR_STYLE.STYLEBOXFLAT_NORMAL_BORDER_COLOR, UIManager.COMMONPROGRESSBAR_STYLE.STYLEBOXFLAT_NORMAL_CORNER_RADIUS)
	
	var fgColor: Color = UIManager.COMMONPROGRESSBAR_STYLE.STYLEBOXFLAT_NORMAL_FG_COLOR1
	if UIManager.COMMONPROGRESSBAR_STYLE.has(fGColorString):
		fgColor = UIManager.COMMONPROGRESSBAR_STYLE.get(fGColorString)
	else:
		HQH.AssertLog("UIManager.COMMONPROGRESSBAR_STYLE not has fGColorString: %s" % fGColorString)
	
	UIManager.SetNewStyleBoxFlat(self, "fg", fgColor, UIManager.COMMONPROGRESSBAR_STYLE.STYLEBOXFLAT_NORMAL_BORDER_WIDTH, UIManager.COMMONPROGRESSBAR_STYLE.STYLEBOXFLAT_NORMAL_BORDER_COLOR, UIManager.COMMONPROGRESSBAR_STYLE.STYLEBOXFLAT_NORMAL_CORNER_RADIUS)
	
	var fontColor: Color = UIManager.COMMONPROGRESSBAR_STYLE.FONT_COLOR_TRANSPARENT
	if UIManager.COMMONPROGRESSBAR_STYLE.has(fontColorString):
		fontColor = UIManager.COMMONPROGRESSBAR_STYLE.get(fontColorString)
	else:
		HQH.AssertLog("UIManager.COMMONPROGRESSBAR_STYLE not has fontColorString: %s" % fontColorString)
	
	self.add_color_override("font_color", fontColor)
