extends Panel

func _ready():
	UIManager.SetNewStyleBoxFlat(self, "panel", UIManager.COMMONBG2_STYLE.STYLEBOXFLAT_PANEL_BG_COLOR, UIManager.COMMONBG2_STYLE.STYLEBOXFLAT_PANEL_BORDER_WIDTH, UIManager.COMMONBG2_STYLE.STYLEBOXFLAT_PANEL_BORDER_COLOR, UIManager.COMMONBG2_STYLE.STYLEBOXFLAT_PANEL_CORNER_RADIUS)	
